name: Keyball44 firmware

on:
  push:
    branches:
      - '*'
    tags:
      - 'keyball44/v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup QMK firmware
      uses: ./.github/actions/setup-qmk

    - name: Install a link to own source
      run: ln -s $(pwd)/qmk_firmware/keyboards/keyball __qmk__/keyboards/keyball

    - run: qmk compile -j 4 -kb keyball/keyball44 -km default

    - run: qmk compile -j 4 -kb keyball/keyball44 -km test

    - run: qmk compile -j 4 -kb keyball/keyball44 -km via

    - name: Archive firmwares
      uses: actions/upload-artifact@v3
      with:
        name: keyball44-firmwares
        path: __qmk__/*.hex

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'keyball44/v')

    steps:
    - name: Download built firmwares
      uses: actions/download-artifact@v3
      with:
        name: keyball44-firmwares
    - name: List assets
      run: ls -l *.hex
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: ${{ contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') }}
        files: |
          *.hex
        fail_on_unmatched_files: true
        generate_release_notes: true
        append_body: true
