name: Release firmwares

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  build:
    name: Build firmwares
    uses: ./.github/workflows/build-all.yml

  deploy:
    name: Deploy firmwares
    runs-on: ubuntu-latest
    needs:
    - build

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Archive Keyball39 firmwares
      uses: ./.github/actions/release-archive
      with: { name: keyball39 }

    - name: Archive Keyball44 firmwares
      uses: ./.github/actions/release-archive
      with: { name: keyball44 }

    - name: Archive Keyball61 firmwares
      uses: ./.github/actions/release-archive
      with: { name: keyball61 }

    - name: Archive Keyball46 firmwares
      uses: ./.github/actions/release-archive
      with: { name: keyball46 }

    - name: Archive One47 firmwares
      uses: ./.github/actions/release-archive
      with: { name: one47 }

    - name: List archives
      run: ls -l *.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: ${{ contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') }}
        files: |
          *.zip
        fail_on_unmatched_files: true
        generate_release_notes: true
        append_body: true
